// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3el4c9Y5GCQlCUpMqAix5LZf8cYN_I8',
    appId: '1:1015649823289:web:b0e81ffe1803f13b7bbbe8',
    messagingSenderId: '1015649823289',
    projectId: 'gfourproject-1e832',
    authDomain: 'gfourproject-1e832.firebaseapp.com',
    storageBucket: 'gfourproject-1e832.appspot.com',
    measurementId: 'G-SETBLN8F48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBNMj2iD-YzFJt1jzRa-IQYbZQQjwUSg',
    appId: '1:1015649823289:android:36512434b8256f9d7bbbe8',
    messagingSenderId: '1015649823289',
    projectId: 'gfourproject-1e832',
    storageBucket: 'gfourproject-1e832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIiwoP326kKKaQXjZ2WEgaMZGKDxyAVCE',
    appId: '1:1015649823289:ios:82615a9f404b07667bbbe8',
    messagingSenderId: '1015649823289',
    projectId: 'gfourproject-1e832',
    storageBucket: 'gfourproject-1e832.appspot.com',
    iosBundleId: 'com.example.gfourproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIiwoP326kKKaQXjZ2WEgaMZGKDxyAVCE',
    appId: '1:1015649823289:ios:82615a9f404b07667bbbe8',
    messagingSenderId: '1015649823289',
    projectId: 'gfourproject-1e832',
    storageBucket: 'gfourproject-1e832.appspot.com',
    iosBundleId: 'com.example.gfourproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm3el4c9Y5GCQlCUpMqAix5LZf8cYN_I8',
    appId: '1:1015649823289:web:89a288fdd7b249a87bbbe8',
    messagingSenderId: '1015649823289',
    projectId: 'gfourproject-1e832',
    authDomain: 'gfourproject-1e832.firebaseapp.com',
    storageBucket: 'gfourproject-1e832.appspot.com',
    measurementId: 'G-1Y1CBJ3RSB',
  );

}